# Eduardo Arango
# eduardoa@nvidia.com
# Software Development Kit 

# user specific environment
HISTCONTROL=erasedups:ignorespace
GIT_EDITOR=vi
KUBE_EDITOR=vi
EDITOR=vi
SDK=$HOME/sdk
PATH=$PATH:/usr/local/go/bin:$HOME/go/bin:$SDK/bin
export SDK GIT_EDITOR HISTCONTROL PATH REGISTRY_AUTH_FILE KUBE_EDITOR EDITOR

# User specific aliases and functions
alias ll="ls --color -lha"
alias lx="ls --color"
alias commit="git commit -s"
alias docker=podman
alias rm='rm -i'
alias c='clear'
alias cp='cp -i'
alias mv='mv -i'
# -> Prevents accidentally clobbering files.
alias mkdir='mkdir -p'
alias h='history'
alias j='jobs -l'
alias which='type -a'
alias ..='cd ..'
# Tmux
alias tinit='tmux new -s eduardo -n workspace'
alias tend='tmux kill-session -t eduardo'

# Enable vi key bindings 
set -o vi

# oc Autocomplete bash 
source <(kubectl completion bash)

# Custom bash functions
# Pretty git log print
function get_git_logs() {

	git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit $1
}
